baseURL = 'https://humanly-studios.github.io/blogs/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# Multilanguage configuration
[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'Humanly Studios Blog'
    weight = 1
    contentDir = 'content/en'
    
    [languages.en.params]
      description = "A blog powered by Hugo and GitHub Pages"
      
    [languages.en.params.homeInfoParams]
      Title = "Humanly Studios Blog"
      Content = "A place for thoughts, ideas, and technical insights."
  
  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    title = 'Blog de Humanly Studios'
    weight = 2
    contentDir = 'content/es'
    
    [languages.es.params]
      description = "Un blog impulsado por Hugo y GitHub Pages"
      
    [languages.es.params.homeInfoParams]
      Title = "Blog de Humanly Studios"
      Content = "Un lugar para pensamientos, ideas y conocimientos técnicos."

[pagination]
  pagerSize = 10

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Humanly Studios Blog"
  description = "A blog powered by Hugo and GitHub Pages"
  keywords = ["blog", "hugo", "github-pages"]
  author = "Sebastian Suarez"
  
  defaultTheme = "light"
  disableThemeToggle = false
  
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "Humanly Studios Blog"
  Content = "A place for thoughts, ideas, and technical insights."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Humanly-Studios"

# English menu
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
    
  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
    weight = 20
    
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 30

# Spanish menu
[languages.es.menu]
  [[languages.es.menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 10
    
  [[languages.es.menu.main]]
    identifier = "posts"
    name = "Artículos"
    url = "posts/"
    weight = 20
    
  [[languages.es.menu.main]]
    identifier = "about"
    name = "Acerca de"
    url = "about/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

[params.assets]
  disableHLJS = false

# Enable Mermaid diagrams
[params.mermaid]
  enable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
